"""add_sharing_and_verification_to_roadmaps

Revision ID: 1d02047296d2
Revises: 3d1782677494
Create Date: 2026-03-27 14:12:12.400087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d02047296d2'
down_revision: Union[str, Sequence[str], None] = '3d1782677494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('roadmaps', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('roadmaps', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmaps', 'tags')
    op.drop_column('roadmaps', 'is_verified')
    op.drop_column('roadmaps', 'is_public')
    # ### end Alembic commands ###
