"""add_summary_to_subnotes

Revision ID: 3d1782677494
Revises: e3c5b7274b57
Create Date: 2026-03-27 13:54:23.975499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1782677494'
down_revision: Union[str, Sequence[str], None] = 'e3c5b7274b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subNotes', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subNotes', 'summary')
    # ### end Alembic commands ###
