"""add_note_stats_fields

Revision ID: e3c5b7274b57
Revises: 0888aeeb9afb
Create Date: 2026-03-27 12:26:59.033384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c5b7274b57'
down_revision: Union[str, Sequence[str], None] = '0888aeeb9afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('complexity', sa.String(length=50), nullable=False))
    op.add_column('notes', sa.Column('time_spent', sa.Integer(), nullable=False))
    op.add_column('notes', sa.Column('last_opened', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notes', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'summary')
    op.drop_column('notes', 'last_opened')
    op.drop_column('notes', 'time_spent')
    op.drop_column('notes', 'complexity')
    # ### end Alembic commands ###
